services:
  - type: web
    name: animas-kitchen
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: NITRO_PRESET
        value: node-server
